#!/bin/bash
echo "🚀 Lab: lab-01-iam-permission-denied"
echo "📋 Category: IAM & Security"
echo ""
echo "🔧 Scenario:"
echo "   IAM AccessDenied: Missing permissions in policy, wrong resource ARN, SCP blocking"
echo ""
echo "💡 Start debugging with:"
echo "   aws sts get-caller-identity"
echo "   Check README.md for specific commands"
