#!/bin/bash
echo "🚀 Lab: lab-04-iam-service-linked-role"
echo "📋 Category: IAM & Security"
echo ""
echo "🔧 Scenario:"
echo "   Service-linked role can't be modified, service needs specific SLR"
echo ""
echo "💡 Start debugging with:"
echo "   aws sts get-caller-identity"
echo "   Check README.md for specific commands"
